services:
  - type: web
    name: movieforcutie
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --chdir src main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: OMDB_API_KEY
        sync: false
